# html lang
language: en

menuname: æ•°å­¦ç¬”è®°

# ä½ çš„æ˜µç§° | Your Name
author: HZP

# main menu navigation
menu:
 
  
  GitHubğŸ§¨: https://github.com/zphuang1998

topmenu:
  é¦–é¡µ: /
  

## ç½‘ç«™æè¿°
description: å­¦ä¹ ç¬”è®°

## ç½‘ç«™å…³é”®è¯ï¼šç”¨è‹±æ–‡é€—å·åˆ†å‰²
keywords: å­¦ä¹ ç¬”è®°

## blogå¤´åƒ
img_src: \pic\avatar.jpg

# ç½‘ç«™æ ‡é¢˜ | Title
logo_title: HZP

#æ ‡è¯­ | Your Slogan
words: æ•°å­¦ç¬”è®°

# æ»‘åŠ¨é¡¶éƒ¨æ¡†
# topmenu:
#  é¦–é¡µ  index: /
#  å…³äº  about: /about

# stylesheets loaded in the <head>
stylesheets:
  - /css/MiHoYo.css

# scripts loaded in the end of the body
scripts:
  - /js/MiHoYo.js

# è¯„è®ºç³»ç»Ÿ | Comments
## åšäº†åŸŸåé™åˆ¶ï¼Œè¯·æ”¹æˆè‡ªå·±çš„ KEY
## è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalse
valine:
  enable: false
  appId:
  appKey:
